### PR TITLE
FIXED draw won't render when not accelerated (eg programmatic screens…

### PR DESCRIPTION
**Pull request by masc3d**
resolving #90

### CODE REVIEW

**Comment by Dimezis** [comment]
Are you sure it fixes the issue?
This method is checking whether we are NOT in hardware accelerated window, which usually happens when the corresponding flag is set in the manifest for an activity or the whole app. 

Also this `if` branch is responsible for drawing children only, not the blur itself.

**Comment by masc3d** [comment]
without hw accel, `super.draw` was entirely skipped.

it's fixed in a way that view is at least rendered (without blur) when taking screenshots via canvas draw on in-memory bitmap or creating a replicate bitmap via `drawingCache`.

with`PixelCopy` it's not an issue as it uses hw, but only available on api level < 26.

**Comment by Dimezis** [comment]
Ah, ok, misunderstood it a bit.
To be honest, I don't remember exactly why did I left this check there.
It was in the commit with a fix for this https://github.com/Dimezis/BlurView/issues/24.
Right now it just seems that I was overthinking back then, but let's not rush with merging it, will do couple of tests.

**Comment by masc3d** [comment]
yes no rush.
 
I also see issues with new offset calculation https://github.com/Dimezis/BlurView/commit/8a60861066e599ef2520f66b4274878b5df0c9e1
amongst others, causing wrong offsets frequently for me with versions >= 1.4.0

I will open another issue for this.

**Comment by Dimezis** [comment]
Your fix is released.
I believe I also fixed the wrong offset calculation in 1.6.0

**Comment by masc3d** [comment]
> Your fix is released.
> I believe I also fixed the wrong offset calculation in 1.6.0

thanks for heads up @Dimezis, looks better, but offset issue still there in some situation. it's possibly related to collapse/expand of `AppBarLayout` but didn't have time to pin it down just yet.

**Comment by Dimezis** [comment]
Maybe it's because you're setting a `fixedTransformationMatrix`?

**Comment by Dimezis** [comment]
Unfortunately, this change led to regression, BlurView now blurs its children as well.
But I guess I have an idea how to fix it, while still being able to do screenshots

**Comment by masc3d** [comment]
> Unfortunately, this change has led to regression, BlurView now blurs its children as well.

if that would be the case it would be entirely unusable?
fix works fine here actually.

**Comment by Dimezis** [comment]
Depends on the children and blur radius. 
For these couple of months, I wasn't even noticing it :)
Try setting a 1px radius and put some TextView inside, you'll see a clear difference with and without the fix

**Comment by masc3d** [comment]
ok. still fail to see how this fix could actually cause regression.

if it does cause a problem, the actual issue is somewhere else and merely been suppressed by not rendering without hw accel.

**Comment by Dimezis** [comment]
To blur stuff, the BlurView is also making a snapshot of the View hierarchy on a software canvas, and previously that code was preventing children of being drawn on that canvas.
Yet somehow I managed to overlook it

**Pull request merged**
