### PR TITLE
Moved blurring to a background thread, and posting an invalidate the view's handler when the bitmap is blurred

### PR DESCRIPTION
**Pull request by premnirmal**
Resolving https://github.com/Dimezis/BlurView/issues/3

### CODE REVIEW

**Comment by Dimezis** [comment]
Thank you, but I have visual artifacts with your approach.
The ublurred version of the background is drawn and visible for a very short period of time before blur will be drawn.
[Unblurred](https://drive.google.com/open?id=0B6M55zORRxrnRkJkY2V0aGhLLTA)
[Blurred in few milliseconds](https://drive.google.com/open?id=0B6M55zORRxrnby16alA3bUhsOG8)

**Comment by premnirmal** [comment]
I see. I think the way to fix it is to move the lines:
```
        internalCanvas.save();
        setupInternalCanvasMatrix();
        drawUnderlyingViews();
        internalCanvas.restore();
```
into the `drawBlurredContent(Canvas)` method so that the internal bitmap and the blurred overlay are set synchronously. Can't seem to get it working yet but I'll keep looking into it

**Comment by Dimezis** [comment]
Actually, the problem is `prepareOverlayForBlur();` in `drawBlurredContent(Canvas)` method. It overdraws all blurred content in overlayBitmap. It must be removed. Also, if you want to use this approach, you need to set canModifyBitmap to false, otherwise it will result in same artifacts.

I'll fix these issues and merge PR.

**Comment by premnirmal** [comment]
thanks, that would be great. do you need write access to my fork?

**Comment by Dimezis** [comment]
As you want. I can merge it locally and then push to my repo. Or you can give me access, I'll push to your repo and merge PR after that.

**Comment by premnirmal** [comment]
Locally is fine. Your call

**Comment by premnirmal** [comment]
That worked! Just tried it out. Thanks @Dimezis

**Comment by Dimezis** [comment]
I'm not really sure right now if we should do it this way...

I don't like the fact that BlurAlgorithm will create additional copy of the bitmap each time it does blur.
But it is necessary to have that 3rd bitmap because the states of the internalBitmap and overlayBitmap are not always synced during the blurring process.

That's the reason I didn't want to do it. I'll consider some other options and test their perfomance a little bit later.

Also, just FYI, you can't cancel the Future the way you tried to do that. A Thread must sleeping or waiting to be able to receive the signal for an interruption.
Moreover, I believe it isn't a good idea anyway, because if we get in such situation, it means that blur process is longer than all operations in main thread, and that `cancel()` in main thread will always cancel the blur task, so it rarely will have a chance to finish at all.

**Comment by premnirmal** [comment]
Ok, makes sense. Thanks for your feedback.

**Pull request closed without merging**
